<?php

namespace Home\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BoxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxRepository extends EntityRepository
{
    /**
     * Simple helper method to store specified entity to database
     *
     * @param $entity
     *
     * @throws \Doctrine\ORM\ORMInvalidArgumentException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function save($entity)
    {
        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();
    }
}
