imports:
    - { resource: repositories.yml }

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Home\PageBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    Home\PageBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Home\PageBundle\Form\BoxType:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', create]
        arguments:
            -  Home\PageBundle\Form\BoxType
